title: "Jaga"
type: "fullstack"
tags: ["fullstack"]
image: "./jaga.png"
description: "A vehicle maintenance app with GPS tracking to monitor kilometers and notify users of service needs based on distance and time."

highlights:
  - "Fullstack Development: Led the fullstack development of the Jaga project using Flutter and NestJS, creating both the frontend and backend infrastructure."
  - "Data Collection: Created a system to collect data from the backend to get car model and car maintenance information, providing users with the necessary details for their vehicles."
  - "Maintenance Reminder: Developed the main function of the app to keep the car/motorcycle data for maintenance reminder, helping users to stay on top of their vehicle maintenance schedules."
  - "Multiple Vehicles: Implemented a feature that allows users to create multiple car/motorcycle entries for maintenance, catering to users with more than one vehicle."
  - "Collaboration: Worked in collaboration with a team member who created the IoT hardware EPS32 for GPS tracking, demonstrating teamwork and cross-functional collaboration."

tools:
  - name: "Typescript"
    logo: "devicon:typescript"

  - name: "NestJS"
    logo: "devicon:nestjs"

  - name: "Dart"
    logo: "devicon:dart"

  - name: "Flutter"
    logo: "devicon:flutter"

sourceCodeUrl: "https://github.com/cattyman919/Jaga"

mediaUrls:
  - "https://bucket.senop.dev/projects/jaga/jaga.png"
